### ISSUE TITLE
Publish a new version with auto encode and with the table functionality

### ISSUE THREAD

**Issue by vikramt24** [NielsLeenheer/EscPosEncoder#77] opened 2022-07-13 07:00 UTC

**Comment by LukasKlement** [comment] 2022-12-22 15:47
Duplicate of https://github.com/NielsLeenheer/EscPosEncoder/issues/71

**Comment by NielsLeenheer** [comment] 2023-04-18 23:40
The release of EscPosEncoder 2 is coming...

**Closed by NielsLeenheer** 2023-04-18 23:40 UTC
